AWSTemplateFormatVersion: 2010-09-09
Description: "This template creates vpc with 2 subnets. 1 private, 1 public"
  
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Ohio-Finance-app
  #Private Subnet        
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2a
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: Ohio-privateSubnet-FinanceApp        
  #Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-2b
      VpcId: !Ref myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Name
          Value: Ohio-publicSubnet-FinanceApp     
  # Custom RT
  CustomRT:
    Type: AWS::EC2::RouteTable
    Properties:a
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: CustomRT-finance-app     

  FinanceIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: FinanceIGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref FinanceIGW

  RouteToIGW:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref CustomRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FinanceIGW
  
  routeTableAssocName:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref CustomRT